version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: priceprobe
      POSTGRES_USER: postgres
    ports:
      - "9042:5432"
  app:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "server.go", "-environment=production"]
    volumes:
      - .:/go/src/github.com/andream16/go-storm
    ports:
      - "80:80"
    depends_on:
      - db
    links:
      - db
